package GUI;


import Negocio.Juego;
import Negocio.Palabra;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;

public class Menu extends javax.swing.JFrame {
    Juego juego;
    
    public Menu() {
        initComponents();
        juego = Juego.getInstance();
        this.setLocationRelativeTo(null);
        panelJuego.setVisible(false);
        panelResultados.setVisible(false);
        panelVocabulario.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        btnJugar = new javax.swing.JButton();
        btnVocabulario = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        panelJuego = new javax.swing.JPanel();
        btnjuego_Menu = new javax.swing.JButton();
        panelVocabulario = new javax.swing.JPanel();
        btnVoca_menu = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        lblEspannol = new javax.swing.JLabel();
        lblMaleku = new javax.swing.JLabel();
        btnAudio = new javax.swing.JButton();
        btnDerecha = new javax.swing.JButton();
        btnIzquierda = new javax.swing.JButton();
        panelResultados = new javax.swing.JPanel();
        btnResults_Menu = new javax.swing.JButton();
        btnRetry = new javax.swing.JButton();
        lblIntentosFallidos = new javax.swing.JLabel();
        lblParejasCorrectas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego de Maleku");
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(534, 373));
        setMinimumSize(new java.awt.Dimension(534, 373));
        setName("Menu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(534, 373));
        setResizable(false);
        setSize(new java.awt.Dimension(534, 373));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.setPreferredSize(new java.awt.Dimension(530, 330));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJugar.setText("jugar");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        panelMenu.add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 257, 120, 47));

        btnVocabulario.setText("Vocabulario");
        btnVocabulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVocabularioActionPerformed(evt);
            }
        });
        panelMenu.add(btnVocabulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 257, 154, 47));

        lblLogo.setBackground(new java.awt.Color(255, 255, 255));
        lblLogo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("imagen de logo");
        lblLogo.setAlignmentX(234.0F);
        lblLogo.setAlignmentY(237.0F);
        lblLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lblLogo.setMaximumSize(new java.awt.Dimension(405, 183));
        lblLogo.setMinimumSize(new java.awt.Dimension(405, 183));
        lblLogo.setPreferredSize(new java.awt.Dimension(405, 183));
        panelMenu.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 38, -1, -1));

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 534, 333));

        panelJuego.setBackground(new java.awt.Color(255, 255, 255));
        panelJuego.setPreferredSize(new java.awt.Dimension(530, 330));
        panelJuego.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnjuego_Menu.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnjuego_Menu.setText("Menú");
        btnjuego_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjuego_MenuActionPerformed(evt);
            }
        });
        panelJuego.add(btnjuego_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 277, 75, 35));

        getContentPane().add(panelJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 534, 333));

        panelVocabulario.setBackground(new java.awt.Color(255, 255, 255));
        panelVocabulario.setPreferredSize(new java.awt.Dimension(530, 330));
        panelVocabulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoca_menu.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnVoca_menu.setText("Menú");
        btnVoca_menu.setToolTipText("Regresar al menú");
        btnVoca_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoca_menuActionPerformed(evt);
            }
        });
        panelVocabulario.add(btnVoca_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 286, 75, 35));

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setToolTipText("");
        lblImagen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelVocabulario.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 27, 284, 279));

        lblEspannol.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        panelVocabulario.add(lblEspannol, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        lblMaleku.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        panelVocabulario.add(lblMaleku, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        btnAudio.setToolTipText("Reproducir audio");
        btnAudio.setBorderPainted(false);
        btnAudio.setContentAreaFilled(false);
        btnAudio.setFocusPainted(false);
        btnAudio.setMaximumSize(new java.awt.Dimension(10000, 10000));
        btnAudio.setMinimumSize(new java.awt.Dimension(1, 1));
        btnAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAudioActionPerformed(evt);
            }
        });
        panelVocabulario.add(btnAudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 70, 70));

        btnDerecha.setToolTipText("Continuar con la palabra siguiente");
        btnDerecha.setBorderPainted(false);
        btnDerecha.setContentAreaFilled(false);
        btnDerecha.setFocusPainted(false);
        btnDerecha.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDerecha.setMaximumSize(new java.awt.Dimension(1000, 1000));
        btnDerecha.setMinimumSize(new java.awt.Dimension(1, 1));
        btnDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerechaActionPerformed(evt);
            }
        });
        panelVocabulario.add(btnDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 85, 61));

        btnIzquierda.setBackground(new java.awt.Color(255, 255, 255));
        btnIzquierda.setToolTipText("Regresar a la palabra anterior");
        btnIzquierda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIzquierda.setBorderPainted(false);
        btnIzquierda.setContentAreaFilled(false);
        btnIzquierda.setFocusPainted(false);
        btnIzquierda.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnIzquierda.setMaximumSize(new java.awt.Dimension(85, 61));
        btnIzquierda.setMinimumSize(new java.awt.Dimension(85, 61));
        btnIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzquierdaActionPerformed(evt);
            }
        });
        panelVocabulario.add(btnIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 85, 61));

        getContentPane().add(panelVocabulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 534, 333));

        panelResultados.setBackground(new java.awt.Color(255, 255, 255));
        panelResultados.setPreferredSize(new java.awt.Dimension(530, 330));
        panelResultados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnResults_Menu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnResults_Menu.setText("Menú");
        btnResults_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResults_MenuActionPerformed(evt);
            }
        });
        panelResultados.add(btnResults_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 112, 50));

        btnRetry.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnRetry.setText("Volver a \nintentar");
        btnRetry.setToolTipText("Regresar al juego");
        btnRetry.setHideActionText(true);
        btnRetry.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRetry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetryActionPerformed(evt);
            }
        });
        panelResultados.add(btnRetry, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 50));

        lblIntentosFallidos.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblIntentosFallidos.setText("Intentos fallidos:");
        panelResultados.add(lblIntentosFallidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 438, 55));

        lblParejasCorrectas.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblParejasCorrectas.setText("Parejas correctas:");
        panelResultados.add(lblParejasCorrectas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 438, 55));

        getContentPane().add(panelResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 534, 333));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnjuego_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjuego_MenuActionPerformed
        panelJuego.setVisible(false);
        panelMenu.setVisible(true);
    }//GEN-LAST:event_btnjuego_MenuActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        panelMenu.setVisible(false);
        panelJuego.setVisible(true);
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnVoca_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoca_menuActionPerformed
        panelVocabulario.setVisible(false);
        panelMenu.setVisible(true);
    }//GEN-LAST:event_btnVoca_menuActionPerformed

    private void btnVocabularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVocabularioActionPerformed
        panelMenu.setVisible(false);
        panelVocabulario.setVisible(true);
        
        btnIzquierda.setIcon(new ImageIcon(juego.recalcularImagen("Imagenes/flecha_izq.png", 85, 61)));
        btnDerecha.setIcon(new ImageIcon(juego.recalcularImagen("Imagenes/flecha_der.png", 85, 61)));
        btnAudio.setIcon(new ImageIcon(juego.recalcularImagen("Imagenes/audio.png", 65, 65)));
        
        juego.palabraPrimera();
        btnIzquierda.setVisible(false);  
            
        Palabra palabraActual = juego.getPalabraActual();
        lblImagen.setIcon(new ImageIcon(juego.recalcularImagen(palabraActual.getimagePath(), 284, 279)));
        lblEspannol.setText("Español: " + palabraActual.getEspannol());
        lblMaleku.setText("Maleku: " + palabraActual.getMaleku());
        
    }//GEN-LAST:event_btnVocabularioActionPerformed

    private void btnRetryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetryActionPerformed
        panelResultados.setVisible(false);
        panelJuego.setVisible(true);
    }//GEN-LAST:event_btnRetryActionPerformed

    private void btnResults_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResults_MenuActionPerformed
        panelResultados.setVisible(false);
        panelMenu.setVisible(true);
    }//GEN-LAST:event_btnResults_MenuActionPerformed

    private void btnAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAudioActionPerformed
        try {
            juego.getPalabraActual().playAudio();
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAudioActionPerformed

    private void btnDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerechaActionPerformed
        juego.palabraSiguiente();
        btnIzquierda.setVisible(true);
     
        if(juego.ultimaPalabra()){
            btnDerecha.setVisible(false);
        }
        Palabra palabraActual = juego.getPalabraActual();
        lblImagen.setIcon(new ImageIcon(juego.recalcularImagen(palabraActual.getimagePath(), 284, 279)));
        lblEspannol.setText("Español: " + palabraActual.getEspannol());
        lblMaleku.setText("Maleku: " + palabraActual.getMaleku());
    }//GEN-LAST:event_btnDerechaActionPerformed

    private void btnIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzquierdaActionPerformed
        juego.palabraAnterior();
        btnDerecha.setVisible(true);
        if(juego.isPrimeraPalabra()){
            btnIzquierda.setVisible(false);
        }
        Palabra palabraActual = juego.getPalabraActual();
        lblImagen.setIcon(new ImageIcon(juego.recalcularImagen(palabraActual.getimagePath(), 284, 279)));
        lblEspannol.setText("Español: " + palabraActual.getEspannol());
        lblMaleku.setText("Maleku: " + palabraActual.getMaleku());
        
    }//GEN-LAST:event_btnIzquierdaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAudio;
    private javax.swing.JButton btnDerecha;
    private javax.swing.JButton btnIzquierda;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnResults_Menu;
    private javax.swing.JButton btnRetry;
    private javax.swing.JButton btnVoca_menu;
    private javax.swing.JButton btnVocabulario;
    private javax.swing.JButton btnjuego_Menu;
    private javax.swing.JLabel lblEspannol;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblIntentosFallidos;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMaleku;
    private javax.swing.JLabel lblParejasCorrectas;
    private javax.swing.JPanel panelJuego;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelResultados;
    private javax.swing.JPanel panelVocabulario;
    // End of variables declaration//GEN-END:variables
}
